services:
  api:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - SERVER_PORT=3000
      - SERVER_HOST=localhost
    command: pnpm run dev
    restart: unless-stopped
